spring:
  datasource:
    url: jdbc:mysql://localhost:3306/companycalendar
    username: companycalendar
    password: KkN7{/uvw}?CKi).hDY8YSM0}YMC3QT

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop

mailgun:
    api:
      base:
        url: https://api.mailgun.net/v3/sandbox80f7417598574294bc4b07da93863028.mailgun.org
      messages:
        url: https://api.mailgun.net/v3/sandbox80f7417598574294bc4b07da93863028.mailgun.org/messages
      username: api
      password: key-04a1bda485a9f3627bf27a871d0250f9-52b6835e-8d60dba0

